name: ami-to-marketplace

on:
  workflow_dispatch:
      inputs:

        ami_id:
          description: "AMI ID to add to the marketplace"
          required: true
          default: ''

        to_marketplace:
          description: "Add the AMI to the marketplace"
          required: true
          type: boolean
          default: true

        notify_mattermost:
          description: "Send notification to Mattermost"
          required: true
          type: boolean
          default: false

jobs:
  build-images:
    name: "Add ${{ inputs.ami_id }} AMI to the marketplace"
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Get Product ID
      run: |
        # PRODUCT_ID=$(aws marketplace-catalog list-change-sets --catalog AWSMarketplace --query 'ChangeSets[?Status==`PENDING`].ProductId' --output text)
        # PRODUCT_ID=$(aws marketplace-catalog list-entities --catalog AWSMarketplace --entity-type AmiProduct --output text)
        PRODUCT_ID=prod-xxxxxxxxxxxxx
        if [[ "${PRODUCT_ID}" == "" || "${PRODUCT_ID}" == "None" ]]; then
          exit 1
        else
          echo "[Debug] Product ID: '${PRODUCT_ID}'"
        fi
        echo "PRODUCT_ID=${PRODUCT_ID}" >> $GITHUB_ENV

    - name: Describe AMI
      run: |
        {
          echo 'AMI_JSON<<EOF'
          aws ec2 describe-images --image-ids=${{ inputs.ami_id}}
          echo EOF
        } >> "$GITHUB_ENV"

    -
      name: "Render the AWS Marketplace change set"
      uses: chuhlomin/render-template@v1
      with:
        template: CI/aws_marketplace_change_set.json.template
        result_path: CI/aws_marketplace_change_set.json
        vars: |
          product_id: ${{ env.PRODUCT_ID }}
          version: ${{ fromJSON(env.AMI_JSON).Tags[0].Value }}
          release_notes:
          ami_id: ${{ inputs.ami_id }}
          access_role_arn: 'arn:aws:iam::764336703387:user/ykohut@almalinux.org'
          os_version: ${{ fromJSON(env.AMI_JSON).Tags[0].Value }}
          instance_type: 't3.medium'

    - name: Print change set
      run: |
        echo "Change set:"
        cat CI/aws_marketplace_change_set.json

    - name: Print AMI summary
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          core.summary
              .addHeading('${{ fromJSON(env.AMI_JSON).Name }}', '4')
              .addHeading('AMI ID: ${{ inputs.ami_id }}', '5')
              .addHeading('PRODUCT ID: ${{ env.PRODUCT_ID }}', '5')
              .addHeading('Public: ${{ inputs.to_marketplace && '✅' || '❌'}}', '5')
              .write()

    - name: Send notification to Mattermost
      uses: mattermost/action-mattermost-notify@master
      if: inputs.notify_mattermost
      with:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_CHANNEL: ${{ vars.MATTERMOST_CHANNEL }}
        MATTERMOST_USERNAME: ${{ github.triggering_actor }}
        TEXT: |
          **${{ fromJSON(env.AMI_JSON).Name }}** AWS AMI, generated by the GitHub [Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          :almalinux: **AMI ID**: `${{ inputs.ami_id }}`

          Release to Marketplace: ${{ inputs.to_marketplace && '✅' || '❌'}}
